window.SUPABASE_URL = 'https://zjmldmkerretnrircslo.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqbWxkbWtlcnJldG5yaXJjc2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3MTgyNjksImV4cCI6MjEwMjI5NDI2OX0.1rxTIWbag6ey1jnsx6klg59MBCZ3E8FfIzc3kHLwOww';
